# Generated by Django 2.0.6 on 2021-02-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210224_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('trad_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trad_amt', models.IntegerField(blank=True, null=True)),
                ('trad_status', models.CharField(max_length=100)),
                ('trad_time', models.TimeField(null=True)),
                ('CheckMacValue', models.CharField(max_length=100)),
            ],
        ),
    ]
