# Generated by Django 2.0.6 on 2021-02-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='trad_amt',
            new_name='trade_amt',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='trad_no',
            new_name='trade_no',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='trad_status',
            new_name='trade_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='trad_time',
            new_name='trade_time',
        ),
        migrations.AlterField(
            model_name='payment',
            name='CheckMacValue',
            field=models.CharField(max_length=300),
        ),
    ]
